# Generated by Django 5.2.8 on 2025-12-17 20:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_scan', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ScanProject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('scan_type', models.CharField(choices=[('repo', 'Repository'), ('zip', 'Archive Upload'), ('single', 'Single File')], default='single', max_length=20)),
                ('status', models.CharField(default='PENDING', max_length=20)),
                ('total_files', models.IntegerField(default=0)),
                ('total_risk_score', models.IntegerField(default=0)),
                ('critical_count', models.IntegerField(default=0)),
                ('high_count', models.IntegerField(default=0)),
                ('medium_count', models.IntegerField(default=0)),
                ('low_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scan_projects', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScanFileResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('filename', models.CharField(max_length=255)),
                ('language', models.CharField(blank=True, max_length=50)),
                ('status', models.CharField(default='UNKNOWN', max_length=20)),
                ('severity', models.CharField(default='SAFE', max_length=20)),
                ('risk_score', models.IntegerField(default=0)),
                ('findings_json', models.TextField(default='[]')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='file_results', to='vuln_scan.scanproject')),
            ],
        ),
        migrations.CreateModel(
            name='ScanUsage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scans_today', models.IntegerField(default=0)),
                ('last_scan_date', models.DateField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='scan_usage', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
