# Generated by Django 5.2.8 on 2025-12-21 00:49

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vuln_scan', '0002_scanproject_scanfileresult_scanusage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scanproject',
            options={},
        ),
        migrations.RemoveField(
            model_name='scanfileresult',
            name='language',
        ),
        migrations.RemoveField(
            model_name='scanproject',
            name='critical_count',
        ),
        migrations.RemoveField(
            model_name='scanproject',
            name='high_count',
        ),
        migrations.RemoveField(
            model_name='scanproject',
            name='low_count',
        ),
        migrations.RemoveField(
            model_name='scanproject',
            name='medium_count',
        ),
        migrations.RemoveField(
            model_name='scanproject',
            name='scan_type',
        ),
        migrations.RemoveField(
            model_name='scanproject',
            name='total_risk_score',
        ),
        migrations.RemoveField(
            model_name='scanusage',
            name='last_scan_date',
        ),
        migrations.RemoveField(
            model_name='scanusage',
            name='scans_today',
        ),
        migrations.AddField(
            model_name='scanproject',
            name='processed_files',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanproject',
            name='repo_url',
            field=models.CharField(blank=True, max_length=512),
        ),
        migrations.AddField(
            model_name='scanproject',
            name='risk_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanusage',
            name='daily_scan_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='scanusage',
            name='last_reset',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scanfileresult',
            name='filename',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='scanfileresult',
            name='severity',
            field=models.CharField(default='SAFE', max_length=10),
        ),
        migrations.AlterField(
            model_name='scanfileresult',
            name='status',
            field=models.CharField(default='PENDING', max_length=20),
        ),
    ]
